import 'dotenv/config'
import cors from 'cors'
import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import bcrypt from 'bcryptjs'
import express, { type NextFunction, type Request, type Response } from 'express'
import helmet from 'helmet'
import jwt from 'jsonwebtoken'
import multer from 'multer'
import { z } from 'zod'
import { connectDatabase } from './db.js'
import { Appointment, AuditLog, Case, Consultation, Department, Document, Doctor, Hospital, Patient, Queue, RecordVersion, Registration, RefreshToken, User } from './models.js'

export type Role = 'PATIENT' | 'DOCTOR' | 'DOCUMENTATION_STAFF'
export type RiskLevel = 'LOW' | 'MODERATE' | 'POTENTIALLY_URGENT' | 'EMERGENCY'
export const CaseStatus = { DRAFT: 'DRAFT', IN_PROGRESS: 'IN_PROGRESS', AI_ASSESSMENT_COMPLETE: 'AI_ASSESSMENT_COMPLETE', READY_FOR_CONSULTATION: 'READY_FOR_CONSULTATION', CONSULTATION_IN_PROGRESS: 'CONSULTATION_IN_PROGRESS', CONSULTATION_COMPLETED: 'CONSULTATION_COMPLETED' } as const
export const DocumentStatus = { UPLOADED: 'UPLOADED', PROCESSING: 'PROCESSING', REVIEW_REQUIRED: 'REVIEW_REQUIRED', REVIEWED: 'REVIEWED', VERIFIED: 'VERIFIED', REJECTED: 'REJECTED' } as const

type TokenPayload = { sub: string; role: Role; patientId?: string; doctorId?: string }
type AuthRequest = Request & { auth?: TokenPayload }
const app = express()
const port = Number(process.env.API_PORT ?? 4000)
const isTestProcess = process.argv.some(argument => argument === '--test' || argument.includes('test_runner'))
const jwtSecret = process.env.JWT_SECRET ?? (isTestProcess ? 'carekare-test-secret' : '')
const refreshSecret = process.env.JWT_REFRESH_SECRET ?? (isTestProcess ? 'carekare-test-refresh-secret' : '')
if (!jwtSecret || !refreshSecret) throw new Error('JWT_SECRET and JWT_REFRESH_SECRET must be configured')
const mockAuth = process.env.MOCK_AUTH !== 'false'
const uploadDirectory = path.resolve(process.env.STORAGE_LOCAL_PATH ?? 'storage')
fs.mkdirSync(uploadDirectory, { recursive: true })
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }))
app.use(cors({ origin: true, credentials: true }))
app.use(express.json({ limit: '2mb' }))
const upload = multer({ dest: uploadDirectory, limits: { fileSize: 10 * 1024 * 1024 }, fileFilter: (_request, file, callback) => callback(null, ['application/pdf', 'image/jpeg', 'image/png'].includes(file.mimetype)) })

export function riskForText(text: string): RiskLevel { if (/chest pain|chest discomfort|difficulty breathing|shortness of breath|fainted|unconscious|stroke/i.test(text)) return 'EMERGENCY'; if (/severe pain|persistent vomiting|high fever|blood in/i.test(text)) return 'POTENTIALLY_URGENT'; if (/pain|vomit|dizz/i.test(text)) return 'MODERATE'; return 'LOW' }
function actionForRisk(level: RiskLevel) { return level === 'EMERGENCY' ? 'SEEK_EMERGENCY_CARE' : level === 'POTENTIALLY_URGENT' ? 'PROMPT_CLINICAL_ATTENTION' : level === 'MODERATE' ? 'ROUTINE_CARE_WITH_WARNING' : 'ROUTINE_CARE' }
export function structuredFindings(complaint: string) { const text = complaint.toLowerCase(); const symptoms = ['stomach', 'abdomen', 'abdominal'].some(word => text.includes(word)) ? ['stomach pain'] : []; if (text.includes('nausea')) symptoms.push('nausea'); if (text.includes('cough')) symptoms.push('cough'); if (text.includes('dizz')) symptoms.push('dizziness'); const duration = text.match(/\d+\s*(?:days?|weeks?)/)?.[0] ?? null; return { symptoms: symptoms.length ? symptoms : ['reported concern'], location: symptoms.includes('stomach pain') ? 'abdomen' : null, duration, severity: null, onset: duration ? 'recent' : null, associatedSymptoms: symptoms.filter(item => item !== 'stomach pain'), relevantHistory: [], medications: [], allergies: [], clinicalContext: symptoms.includes('stomach pain') || symptoms.includes('nausea') ? 'Gastrointestinal' : 'General Medicine', recommendedDepartment: symptoms.includes('stomach pain') || symptoms.includes('nausea') ? 'Gastroenterology' : 'General Medicine', uncertainties: [], confidence: 0.92 } }
function hash(value: string) { return crypto.createHash('sha256').update(value).digest('hex') }
function accessToken(user: TokenPayload) { return jwt.sign(user, jwtSecret, { expiresIn: '15m' }) }
async function audit(actorId: string | undefined, action: string, entityType: string, entityId: string, metadata?: unknown) { await AuditLog.create({ actorId, action, entityType, entityId, metadata }).catch(() => undefined) }
async function issueTokens(user: { _id: unknown; role: Role; patientId?: string; doctorId?: string }) { const id = String(user._id); const refreshToken = jwt.sign({ sub: id }, refreshSecret, { expiresIn: '30d' }); await RefreshToken.create({ userId: id, tokenHash: hash(refreshToken), expiresAt: new Date(Date.now() + 30 * 86400000) }); return { accessToken: accessToken({ sub: id, role: user.role, patientId: user.patientId, doctorId: user.doctorId }), refreshToken } }
async function requireAuth(request: AuthRequest, response: Response, next: NextFunction) { const value = request.header('authorization')?.replace(/^Bearer\s+/i, ''); if (!value) return response.status(401).json({ error: 'Authentication required' }); try { request.auth = jwt.verify(value, jwtSecret) as TokenPayload; next() } catch { response.status(401).json({ error: 'Invalid or expired access token' }) } }
function requireRole(...roles: Role[]) { return (request: AuthRequest, response: Response, next: NextFunction) => roles.includes(request.auth?.role as Role) ? next() : response.status(403).json({ error: 'Insufficient permissions' }) }
async function userWithProfile(user: any) { const patient: any = await Patient.findOne({ userId: String(user?._id) }).lean(); const doctor: any = await Doctor.findOne({ userId: String(user?._id) }).lean(); return { ...user, patientId: patient?._id?.toString(), doctorId: doctor?._id?.toString(), patient, doctor } }
async function patientOf(request: AuthRequest) { return request.auth?.patientId ? Patient.findById(request.auth.patientId) : null }
async function ownedCase(request: AuthRequest, id: string) { const item: any = await Case.findById(id).lean(); if (!item || request.auth?.role === 'PATIENT' && item.patientId !== request.auth.patientId) return null; return item }

app.get('/', (_request, response) => response.json({ status: 'ok', service: 'carekare-api', health: '/health' }))
app.get('/health', (_request, response) => response.json({ status: 'ok', service: 'carekare-api', persistence: 'mongodb' }))
app.post('/auth/patient/login', async (request, response, next) => { try { const identifier = z.string().min(1).parse(request.body?.identifier); let patient: any = await Patient.findOne({ $or: [{ abhaId: identifier }, { aadhaarHash: hash(identifier) }] }).lean(); if (!patient && mockAuth) patient = await Patient.findOne().lean(); if (!patient) return response.status(401).json({ error: 'Identity not found' }); const user: any = await User.findById(patient.userId).lean(); if (!user) return response.status(503).json({ error: 'Patient account is incomplete' }); const tokens = await issueTokens({ _id: user._id, role: 'PATIENT', patientId: String(patient._id) }); await audit(String(user._id), 'LOGIN', 'Patient', String(patient._id), { mock: mockAuth }); response.json({ ...tokens, user: { id: String(user._id), role: 'PATIENT', name: patient.name, abhaId: patient.abhaId }, mock: mockAuth }) } catch (error) { next(error) } })
app.post('/auth/doctor/login', async (request, response, next) => { try { const identifier = z.string().min(1).parse(request.body?.identifier); let user: any = await User.findOne({ email: identifier, role: 'DOCTOR' }).lean(); let doctor: any = user && await Doctor.findOne({ userId: String(user._id) }).lean(); if (!doctor && /^[a-f\d]{24}$/i.test(identifier)) { doctor = await Doctor.findById(identifier).lean(); user = doctor && await User.findById(doctor.userId).lean() } if (!doctor && mockAuth) { doctor = await Doctor.findOne().lean(); user = doctor && await User.findById(doctor.userId).lean() } if (!doctor || !user) return response.status(401).json({ error: 'Invalid doctor credentials' }); if (!mockAuth && (!request.body?.password || !user.passwordHash || !(await bcrypt.compare(request.body.password, user.passwordHash)))) return response.status(401).json({ error: 'Invalid doctor credentials' }); const tokens = await issueTokens({ _id: user._id, role: 'DOCTOR', doctorId: String(doctor._id) }); await audit(String(user._id), 'LOGIN', 'Doctor', String(doctor._id), { mock: mockAuth }); response.json({ ...tokens, user: { id: String(user._id), role: 'DOCTOR', name: doctor.name, department: doctor.department }, mock: mockAuth }) } catch (error) { next(error) } })
app.post('/auth/patient/register', async (request, response, next) => { try { const data = z.object({ name: z.string().trim().min(2).max(120), abhaId: z.string().trim().min(4).max(40), email: z.string().email().optional() }).parse(request.body); if (await Patient.exists({ abhaId: data.abhaId })) return response.status(409).json({ error: 'An account already exists for this ABHA ID' }); if (data.email && await User.exists({ email: data.email })) return response.status(409).json({ error: 'An account already exists for this email' }); const user: any = await User.create({ email: data.email, role: 'PATIENT' }); const patient: any = await Patient.create({ userId: String(user._id), name: data.name, abhaId: data.abhaId }); const tokens = await issueTokens({ _id: user._id, role: 'PATIENT', patientId: String(patient._id) }); await audit(String(user._id), 'ACCOUNT_CREATED', 'Patient', String(patient._id)); response.status(201).json({ ...tokens, user: { id: String(user._id), role: 'PATIENT', name: patient.name, abhaId: patient.abhaId }, mock: mockAuth }) } catch (error) { next(error) } })
app.post('/auth/doctor/register', async (request, response, next) => { try { const data = z.object({ name: z.string().trim().min(2).max(120), email: z.string().email(), password: z.string().min(8).max(200), specialty: z.string().trim().min(2).max(120), department: z.string().trim().min(2).max(120) }).parse(request.body); if (await User.exists({ email: data.email })) return response.status(409).json({ error: 'An account already exists for this email' }); const user: any = await User.create({ email: data.email, passwordHash: await bcrypt.hash(data.password, 10), role: 'DOCTOR' }); const doctor: any = await Doctor.create({ userId: String(user._id), name: data.name, specialty: data.specialty, department: data.department }); const tokens = await issueTokens({ _id: user._id, role: 'DOCTOR', doctorId: String(doctor._id) }); await audit(String(user._id), 'ACCOUNT_CREATED', 'Doctor', String(doctor._id)); response.status(201).json({ ...tokens, user: { id: String(user._id), role: 'DOCTOR', name: doctor.name, department: doctor.department }, mock: mockAuth }) } catch (error) { next(error) } })
app.post('/auth/refresh', async (request, response, next) => { try { const raw = z.string().min(1).parse(request.body?.refreshToken); const decoded = jwt.verify(raw, refreshSecret) as { sub: string }; const record: any = await RefreshToken.findOne({ userId: decoded.sub, tokenHash: hash(raw), revokedAt: null, expiresAt: { $gt: new Date() } }).lean(); if (!record) return response.status(401).json({ error: 'Refresh token is invalid' }); const user: any = await userWithProfile(await User.findById(decoded.sub).lean()); response.json({ accessToken: accessToken({ sub: decoded.sub, role: user.role, patientId: user.patientId, doctorId: user.doctorId }) }) } catch (error) { next(error) } })
app.post('/auth/logout', requireAuth, async (request: AuthRequest, response, next) => { try { await RefreshToken.updateMany({ userId: request.auth!.sub, revokedAt: null }, { revokedAt: new Date() }); response.status(204).send() } catch (error) { next(error) } })

app.get('/patients/me', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { const patient = await patientOf(request); patient ? response.json(patient) : response.status(404).json({ error: 'Patient profile not found' }) } catch (error) { next(error) } })
app.get('/patients/me/cases', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { const cases: any[] = await Case.find({ patientId: request.auth!.patientId }).sort({ createdAt: -1 }).lean(); const departments = await Department.find({ _id: { $in: cases.map(item => item.departmentId).filter(Boolean) } }).lean(); response.json(cases.map(item => ({ ...item, department: departments.find(department => String(department._id) === item.departmentId) ?? null }))) } catch (error) { next(error) } })
app.get('/patients/me/documents', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { response.json(await Document.find({ patientId: request.auth!.patientId }).sort({ createdAt: -1 }).lean()) } catch (error) { next(error) } })
app.get('/patients/me/history', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { const patient = await patientOf(request); if (!patient) return response.status(404).json({ error: 'Patient profile not found' }); const [cases, documents, consultations, appointments, queues, registrations] = await Promise.all([Case.find({ patientId: patient._id }).sort({ createdAt: -1 }).lean(), Document.find({ patientId: patient._id, processingStatus: 'VERIFIED' }).sort({ createdAt: -1 }).lean(), Consultation.find({ patientId: patient._id }).sort({ createdAt: -1 }).lean(), Appointment.find({ patientId: patient._id }).sort({ scheduledAt: 1 }).lean(), Queue.find({ patientId: patient._id }).sort({ createdAt: -1 }).lean(), Registration.find({ patientId: patient._id }).sort({ createdAt: -1 }).lean()]); response.json({ abhaId: patient.abhaId, cases, documents, consultations, appointments, queues, registrations }) } catch (error) { next(error) } })
app.get('/departments', requireAuth, async (_request, response, next) => { try { response.json(await Department.find().sort({ name: 1 }).lean()) } catch (error) { next(error) } })

app.post('/cases', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { const complaint = z.string().min(3).max(4000).parse(request.body?.complaint); const patient = await patientOf(request); if (!patient) return response.status(404).json({ error: 'Patient profile not found' }); const findings = structuredFindings(complaint); const riskLevel = riskForText(complaint); const department: any = await Department.findOne({ name: new RegExp(findings.recommendedDepartment, 'i') }).lean(); const item: any = await Case.create({ _id: `CK-${new Date().getFullYear()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`, patientId: String(patient._id), departmentId: department?._id?.toString(), status: riskLevel === 'EMERGENCY' ? CaseStatus.IN_PROGRESS : CaseStatus.AI_ASSESSMENT_COMPLETE, complaint, aiFindings: findings, riskLevel, symptoms: findings.symptoms.map(name => ({ name })), riskAssessments: [{ level: riskLevel, action: actionForRisk(riskLevel), acknowledged: false }] }); await audit(request.auth!.sub, 'CASE_CREATED', 'Case', item._id, { riskLevel }); response.status(201).json({ ...item.toObject(), department }) } catch (error) { next(error) } })
app.get('/cases/:id', requireAuth, async (request: AuthRequest, response, next) => { try { const item = await ownedCase(request, String(request.params.id)); item ? response.json(item) : response.status(404).json({ error: 'Case not found or not authorized' }) } catch (error) { next(error) } })
app.post('/cases/:id/responses', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { const item = await ownedCase(request, String(request.params.id)); if (!item) return response.status(404).json({ error: 'Case not found or not authorized' }); const answer = request.body?.answer; await Case.updateOne({ _id: item._id }, { $push: { responses: { questionId: request.body?.questionId, answer, createdAt: new Date() } } }); response.status(201).json({ caseId: item._id, answer }) } catch (error) { next(error) } })
app.post('/cases/:id/risk-assessment', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { const item: any = await ownedCase(request, String(request.params.id)); if (!item) return response.status(404).json({ error: 'Case not found or not authorized' }); const level = riskForText(`${item.complaint ?? ''} ${JSON.stringify(item.responses ?? [])}`); const assessment = { level, action: actionForRisk(level), acknowledged: Boolean(request.body?.acknowledged), createdAt: new Date() }; await Case.updateOne({ _id: item._id }, { $set: { riskLevel: level }, $push: { riskAssessments: assessment } }); response.json({ ...assessment, emergency: level === 'EMERGENCY' }) } catch (error) { next(error) } })
app.post('/cases/:id/department', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { const item: any = await ownedCase(request, String(request.params.id)); const departmentId = z.string().min(1).parse(request.body?.departmentId); if (!item) return response.status(404).json({ error: 'Case not found or not authorized' }); if (item.riskLevel === 'EMERGENCY') return response.status(409).json({ error: 'Emergency cases cannot be routed through ordinary departments' }); const updated = await Case.findByIdAndUpdate(item._id, { departmentId }, { new: true }).lean(); response.json(updated) } catch (error) { next(error) } })
app.post('/cases/:id/summary', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { const item: any = await ownedCase(request, String(request.params.id)); if (!item) return response.status(404).json({ error: 'Case not found or not authorized' }); if (item.riskLevel === 'EMERGENCY') return response.status(409).json({ error: 'Emergency guidance must be followed before routine handoff' }); const content = { ...(item.aiFindings ?? {}), mainComplaint: item.complaint, riskLevel: item.riskLevel, disclaimer: 'AI organizes information; a clinician provides diagnosis and treatment.' }; await Case.findByIdAndUpdate(item._id, { status: CaseStatus.READY_FOR_CONSULTATION, $push: { summaries: { content, confidence: 0.92, createdAt: new Date() } } }); response.json({ caseId: item._id, content, confidence: 0.92 }) } catch (error) { next(error) } })

app.get('/doctor/dashboard', requireAuth, requireRole('DOCTOR'), async (_request, response, next) => { try { const [activeCases, reportsForReview, completedConsultations, recentPatients] = await Promise.all([Case.countDocuments({ status: { $in: [CaseStatus.READY_FOR_CONSULTATION, CaseStatus.CONSULTATION_IN_PROGRESS] } }), Document.countDocuments({ processingStatus: 'REVIEW_REQUIRED' }), Consultation.countDocuments({ status: 'COMPLETED' }), Patient.find().sort({ createdAt: -1 }).limit(5).select('name abhaId').lean()]); response.json({ activeCases, reportsForReview, completedConsultations, recentPatients }) } catch (error) { next(error) } })
app.get('/doctor/cases', requireAuth, requireRole('DOCTOR'), async (_request, response, next) => { try { const cases: any[] = await Case.find({ status: { $in: [CaseStatus.READY_FOR_CONSULTATION, CaseStatus.CONSULTATION_IN_PROGRESS] } }).sort({ createdAt: -1 }).lean(); const patients = await Patient.find({ _id: { $in: cases.map(item => item.patientId) } }).lean(); response.json(cases.map(item => ({ ...item, patient: patients.find(patient => String(patient._id) === item.patientId) ?? null }))) } catch (error) { next(error) } })
app.get('/doctor/cases/:id', requireAuth, requireRole('DOCTOR'), async (request, response, next) => { try { const item: any = await Case.findById(request.params.id).lean(); if (!item) return response.status(404).json({ error: 'Case not found' }); item.patient = await Patient.findById(item.patientId).lean(); item.documents = await Document.find({ caseId: item._id }).lean(); item.consultations = await Consultation.find({ caseId: item._id }).lean(); response.json(item) } catch (error) { next(error) } })
app.post('/doctor/consultations', requireAuth, requireRole('DOCTOR'), async (request: AuthRequest, response, next) => { try { const doctor: any = await Doctor.findById(request.auth!.doctorId).lean(); const data = z.object({ caseId: z.string(), clinicalAssessment: z.string().optional(), clinicalNotes: z.string().optional(), diagnosis: z.array(z.object({ name: z.string().min(1), code: z.string().optional() })).default([]), prescription: z.unknown().optional(), investigations: z.array(z.unknown()).default([]), treatmentPlan: z.string().optional(), followUp: z.unknown().optional(), status: z.enum(['DRAFT', 'COMPLETED']).default('DRAFT') }).parse(request.body); const item: any = await Case.findById(data.caseId).lean(); if (!doctor || !item) return response.status(404).json({ error: 'Doctor or case not found' }); if (data.status === 'COMPLETED' && !data.diagnosis.length) return response.status(400).json({ error: 'Doctor confirmation requires at least one diagnosis' }); const consultation = await Consultation.create({ ...data, patientId: item.patientId, doctorId: String(doctor._id), completedAt: data.status === 'COMPLETED' ? new Date() : undefined }); await Case.findByIdAndUpdate(item._id, { status: data.status === 'COMPLETED' ? CaseStatus.CONSULTATION_COMPLETED : CaseStatus.CONSULTATION_IN_PROGRESS }); await audit(request.auth!.sub, 'CONSULTATION_CREATED', 'Consultation', String(consultation._id), { status: data.status }); response.status(201).json(consultation) } catch (error) { next(error) } })

app.post('/documents/upload', requireAuth, requireRole('PATIENT'), upload.single('file'), async (request: AuthRequest, response, next) => { try { if (!request.file) return response.status(400).json({ error: 'A PDF, JPG, JPEG, or PNG file is required' }); const patient = await patientOf(request); if (!patient) return response.status(404).json({ error: 'Patient profile not found' }); const fileHash = await new Promise<string>((resolve, reject) => { const stream = fs.createReadStream(request.file!.path); const digest = crypto.createHash('sha256'); stream.on('data', chunk => digest.update(chunk)); stream.on('end', () => resolve(digest.digest('hex'))); stream.on('error', reject) }); const item = await Document.create({ patientId: String(patient._id), caseId: request.body.caseId, type: request.body.type ?? 'OTHER', fileName: request.file.originalname, storagePath: request.file.path, mimeType: request.file.mimetype, fileSize: request.file.size, fileHash, processingStatus: DocumentStatus.UPLOADED }); response.status(201).json(item) } catch (error) { next(error) } })
app.get('/documents/:id', requireAuth, async (request: AuthRequest, response, next) => { try { const item: any = await Document.findById(request.params.id).lean(); if (!item || request.auth?.role === 'PATIENT' && item.patientId !== request.auth.patientId) return response.status(404).json({ error: 'Document not found or not authorized' }); response.json(item) } catch (error) { next(error) } })
app.get('/documents/:id/original', requireAuth, async (request: AuthRequest, response, next) => { try { const item: any = await Document.findById(request.params.id).lean(); if (!item || request.auth?.role === 'PATIENT' && item.patientId !== request.auth.patientId || !fs.existsSync(item.storagePath)) return response.status(404).json({ error: 'Original file is unavailable' }); response.type(item.mimeType).sendFile(path.resolve(item.storagePath)) } catch (error) { next(error) } })
app.post('/documents/:id/process', requireAuth, async (request, response, next) => { try { const item: any = await Document.findById(request.params.id).lean(); if (!item) return response.status(404).json({ error: 'Document not found' }); const extractedData = item.type === 'PRESCRIPTION' ? { diagnosis: 'Gastroesophageal reflux', medicines: [{ medicineName: 'Pantoprazole', dose: '40 mg', frequency: 'Once daily', duration: '14 days' }] } : { results: [{ testName: 'Hemoglobin', value: '12.5', unit: 'g/dL', referenceRange: '12-16 g/dL', flag: 'NORMAL' }] }; const version = (item.versions?.length ?? 0) + 1; const updated = await Document.findByIdAndUpdate(item._id, { processingStatus: DocumentStatus.REVIEW_REQUIRED, classification: item.type, classificationConfidence: 0.94, rawText: 'Mock OCR text extracted from the original document.', extractedData, extractionConfidence: 0.94, $push: { versions: { version, data: extractedData, createdAt: new Date() } } }, { new: true }).lean(); response.json(updated) } catch (error) { next(error) } })
app.get('/doctor/documents', requireAuth, requireRole('DOCTOR', 'DOCUMENTATION_STAFF'), async (_request, response, next) => { try { const documents: any[] = await Document.find({ processingStatus: 'REVIEW_REQUIRED' }).sort({ createdAt: 1 }).lean(); const patients = await Patient.find({ _id: { $in: documents.map(item => item.patientId) } }).lean(); response.json(documents.map(item => ({ ...item, patient: patients.find(patient => String(patient._id) === item.patientId) ?? null }))) } catch (error) { next(error) } })
app.post('/documents/:id/review', requireAuth, requireRole('DOCTOR', 'DOCUMENTATION_STAFF'), async (request: AuthRequest, response, next) => { try { const action = z.enum(['VERIFY', 'EDIT', 'REJECT', 'MARK_UNRELATED']).parse(request.body?.action); const item: any = await Document.findById(request.params.id).lean(); if (!item) return response.status(404).json({ error: 'Document not found' }); const status = action === 'VERIFY' ? DocumentStatus.VERIFIED : action === 'REJECT' || action === 'MARK_UNRELATED' ? DocumentStatus.REJECTED : DocumentStatus.REVIEWED; const update: any = { processingStatus: status, $push: { reviews: { action, reviewerId: request.auth!.sub, notes: request.body?.notes, createdAt: new Date() } } }; if (action === 'EDIT' && request.body?.structuredData) { update.extractedData = request.body.structuredData; update.$push.versions = { version: (item.versions?.length ?? 0) + 1, data: request.body.structuredData, createdAt: new Date() } } const saved: any = await Document.findByIdAndUpdate(item._id, update, { new: true }).lean(); if (action === 'VERIFY') await RecordVersion.create({ recordId: String(item._id), patientId: item.patientId, version: 1, structuredRecord: item.extractedData, createdBy: request.auth!.sub, role: request.auth!.role }); response.json(saved) } catch (error) { next(error) } })

app.get('/appointments/availability', requireAuth, async (_request, response, next) => { try { const doctors: any[] = await Doctor.find().limit(10).lean(); response.json(doctors.map(doctor => ({ doctorId: String(doctor._id), doctorName: doctor.name, specialty: doctor.specialty, department: doctor.department, scheduledAt: new Date(Date.now() + 86400000).toISOString(), available: true }))) } catch (error) { next(error) } })
app.post('/appointments', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { const data = z.object({ caseId: z.string().optional(), doctorId: z.string(), departmentId: z.string().optional(), hospitalId: z.string().optional(), scheduledAt: z.string().datetime() }).parse(request.body); response.status(201).json(await Appointment.create({ ...data, patientId: request.auth!.patientId, scheduledAt: new Date(data.scheduledAt), status: 'BOOKED' })) } catch (error) { next(error) } })
app.get('/appointments', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { response.json(await Appointment.find({ patientId: request.auth!.patientId }).sort({ scheduledAt: 1 }).lean()) } catch (error) { next(error) } })
app.post('/queues/join', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { const count = await Queue.countDocuments({ status: 'WAITING', departmentId: request.body.departmentId }); response.status(201).json(await Queue.create({ ...request.body, patientId: request.auth!.patientId, token: `A${String(count + 1).padStart(2, '0')}`, position: count + 1, status: 'WAITING' })) } catch (error) { next(error) } })
app.post('/registrations', requireAuth, requireRole('PATIENT'), async (request: AuthRequest, response, next) => { try { response.status(201).json(await Registration.create({ ...request.body, patientId: request.auth!.patientId, registrationNumber: `REG-${Date.now().toString().slice(-8)}`, status: 'CREATED' })) } catch (error) { next(error) } })

app.use((_request, response) => response.status(404).json({ error: 'Route not found' }))
app.use((error: unknown, _request: Request, response: Response, _next: NextFunction) => { console.error(error); const message = error instanceof Error ? error.message : ''; if (message.includes('File type') || error instanceof multer.MulterError) return response.status(400).json({ error: 'Upload a PDF, JPG, JPEG, or PNG file up to 10 MB' }); response.status(500).json({ error: 'Unexpected server error' }) })
export async function seedIfEmpty() {
  const patientCount = await Patient.countDocuments()
  if (patientCount === 0) {
    console.log('Database is empty. Seeding initial demo records...')
    const passwordHash = bcrypt.hashSync('CareKareDemo2026!', 10)
    const [city, sunrise] = await Hospital.create([{ name: 'City Care Hospital' }, { name: 'Sunrise Medical Centre' }])
    const [general, gastro, cardiology, diagnostics] = await Department.create([
      { name: 'General Medicine', hospitalId: String(city._id) },
      { name: 'Gastroenterology', hospitalId: String(city._id) },
      { name: 'Cardiology', hospitalId: String(city._id) },
      { name: 'Diagnostics', hospitalId: String(sunrise._id) },
    ])
    const patientSeeds = [
      { email: 'ananya@carekare.demo', name: 'Ananya Sharma', abhaId: '91-4821-6630-1198' },
      { email: 'ravi@carekare.demo', name: 'Ravi Kumar', abhaId: '91-4821-6630-2209' },
      { email: 'meera@carekare.demo', name: 'Meera Iyer', abhaId: '91-4821-6630-3310' },
    ]
    const patients = []
    for (const seed of patientSeeds) {
      const user: any = await User.create({ email: seed.email, passwordHash, role: 'PATIENT' })
      patients.push(await Patient.create({ userId: String(user._id), name: seed.name, abhaId: seed.abhaId }))
    }
    const doctorSeeds = [
      { email: 'doctor@carekare.demo', name: 'Dr. Rohan Mehta', specialty: 'General Medicine', department: 'General Medicine' },
      { email: 'kavya@carekare.demo', name: 'Dr. Kavya Nair', specialty: 'Gastroenterology', department: 'Gastroenterology' },
    ]
    const doctors = []
    for (const seed of doctorSeeds) {
      const user: any = await User.create({ email: seed.email, passwordHash, role: 'DOCTOR' })
      doctors.push(await Doctor.create({ userId: String(user._id), name: seed.name, specialty: seed.specialty, department: seed.department }))
    }
    const sampleCases: any[] = [
      { _id: 'CK-2026-0091', patientId: String(patients[0]._id), departmentId: String(gastro._id), status: 'READY_FOR_CONSULTATION', complaint: 'Stomach discomfort and nausea for three days', riskLevel: 'LOW' },
      { _id: 'CK-2026-0074', patientId: String(patients[0]._id), departmentId: String(general._id), status: 'CONSULTATION_COMPLETED', complaint: 'Seasonal cough since Monday', riskLevel: 'LOW' },
      { _id: 'CK-2026-0112', patientId: String(patients[1]._id), departmentId: String(general._id), status: 'DRAFT', complaint: 'Persistent headache', riskLevel: 'MODERATE' },
      { _id: 'CK-2026-0108', patientId: String(patients[2]._id), departmentId: String(cardiology._id), status: 'IN_PROGRESS', complaint: 'Severe chest discomfort', riskLevel: 'POTENTIALLY_URGENT' },
    ]
    await Case.insertMany(sampleCases.map(item => ({ ...item, aiFindings: { symptoms: item.complaint.split(' ').slice(0, 4), recommendedDepartment: item.departmentId === String(gastro._id) ? 'Gastroenterology' : 'General Medicine', confidence: 0.92 }, riskAssessments: [{ level: item.riskLevel, action: 'ROUTINE_CARE' }] })))
    await Document.create({ patientId: String(patients[0]._id), caseId: 'CK-2026-0091', type: 'LAB_REPORT', fileName: 'Blood test report.pdf', storagePath: 'demo/blood-test-report.pdf', mimeType: 'application/pdf', fileSize: 128000, fileHash: 'demo-lab-hash', processingStatus: 'REVIEW_REQUIRED', classification: 'Lab Report', extractedData: { results: [{ testName: 'Hemoglobin', value: '12.5', unit: 'g/dL', referenceRange: '12-16 g/dL' }] }, extractionConfidence: 0.94 })
    await Document.create({ patientId: String(patients[0]._id), caseId: 'CK-2026-0091', type: 'PRESCRIPTION', fileName: 'Previous prescription.pdf', storagePath: 'demo/previous-prescription.pdf', mimeType: 'application/pdf', fileSize: 89000, fileHash: 'demo-prescription-hash', processingStatus: 'VERIFIED', classification: 'Prescription', extractedData: { diagnosis: 'GERD', medicines: [{ medicineName: 'Pantoprazole', dose: '40 mg', frequency: 'Once daily', duration: '14 days' }] }, extractionConfidence: 0.96 })
    await Consultation.create({ caseId: 'CK-2026-0074', patientId: String(patients[0]._id), doctorId: String(doctors[0]._id), clinicalAssessment: 'Symptoms consistent with a self-limited seasonal cough.', clinicalNotes: 'Demo completed consultation.', diagnoses: [{ name: 'Seasonal cough', confirmed: true }], prescriptions: [{ items: [{ medicineName: 'Supportive care', duration: '5 days' }] }], treatmentPlan: 'Continue supportive care and return if symptoms worsen.', status: 'COMPLETED', completedAt: new Date() })
    await Appointment.create({ patientId: String(patients[0]._id), caseId: 'CK-2026-0091', doctorId: String(doctors[1]._id), hospitalId: String(city._id), departmentId: String(gastro._id), scheduledAt: new Date(Date.now() + 86400000), status: 'BOOKED' })
    await Queue.create({ patientId: String(patients[1]._id), caseId: 'CK-2026-0112', hospitalId: String(city._id), departmentId: String(general._id), token: 'A23', position: 5, status: 'WAITING' })
    await Registration.create({ patientId: String(patients[2]._id), caseId: 'CK-2026-0108', hospitalId: String(sunrise._id), departmentId: String(diagnostics._id), registrationNumber: 'REG-26090101', status: 'CREATED' })
    console.log('Seeded initial demo records successfully.')
  }
}

function startSelfPing() {
  const targetUrl = process.env.RENDER_EXTERNAL_URL ?? process.env.SELF_PING_URL ?? `http://localhost:${port}`
  const intervalMs = 10 * 60 * 1000
  setInterval(() => {
    fetch(`${targetUrl}/health`)
      .then(res => res.json())
      .then(() => console.log(`[Self-Ping] Keep-alive heartbeat sent to ${targetUrl}/health`))
      .catch(err => console.warn('[Self-Ping] Keep-alive error:', err.message))
  }, intervalMs)
  console.log(`[Self-Ping] Keep-alive timer active (every 10 mins) targeting ${targetUrl}`)
}

if (process.env.NODE_ENV !== 'test' && !isTestProcess) {
  connectDatabase().then(async () => {
    await seedIfEmpty().catch(err => console.error('Auto-seed error:', err))
    app.listen(port, () => {
      console.log(`CareKare API listening on http://localhost:${port}`)
      startSelfPing()
    })
  }).catch(error => { console.error('MongoDB connection failed', error); process.exitCode = 1 })
}
export { app }
