import 'dotenv/config'
import cors from 'cors'
import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import bcrypt from 'bcryptjs'
import express, { type NextFunction, type Request, type Response } from 'express'
import helmet from 'helmet'
import jwt from 'jsonwebtoken'
import multer from 'multer'
import { Prisma, PrismaClient, Role, CaseStatus, DocumentStatus, RiskLevel } from '@prisma/client'
import { z } from 'zod'

const prisma = new PrismaClient()
const app = express()
const port = Number(process.env.API_PORT ?? 4000)
const jwtSecret = process.env.JWT_SECRET ?? 'carekare-development-secret-change-me'
const refreshSecret = process.env.JWT_REFRESH_SECRET ?? 'carekare-development-refresh-secret-change-me'
const mockAuth = process.env.MOCK_AUTH !== 'false'
const uploadDirectory = path.resolve(process.env.STORAGE_LOCAL_PATH ?? 'storage')
fs.mkdirSync(uploadDirectory, { recursive: true })

app.use(helmet())
const allowedOrigins = new Set((process.env.WEB_ORIGIN ?? 'http://localhost:5173').split(',').map((origin) => origin.trim()))
app.use(cors({ origin: (origin, callback) => { if (!origin || allowedOrigins.has(origin) || /^https?:\/\/localhost:\d+$/.test(origin)) return callback(null, true); callback(new Error('Origin is not allowed')) } }))
app.use(express.json({ limit: '2mb' }))

const upload = multer({
  dest: uploadDirectory,
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter: (_request, file, callback) => callback(null, ['application/pdf', 'image/jpeg', 'image/png'].includes(file.mimetype)),
})

const authSchema = z.object({ identifier: z.string().min(1), password: z.string().optional() })
const complaintSchema = z.object({ complaint: z.string().min(3).max(4000), hospitalId: z.string().optional() })
const responseSchema = z.object({ questionId: z.string().optional(), answer: z.unknown() })
const departmentSchema = z.object({ departmentId: z.string().min(1), acknowledged: z.boolean().optional() })
const riskSchema = z.object({ acknowledged: z.boolean().optional() })
const consultationSchema = z.object({ caseId: z.string(), clinicalAssessment: z.string().optional(), clinicalNotes: z.string().optional(), diagnosis: z.array(z.object({ name: z.string().min(1), code: z.string().optional() })).default([]), prescription: z.object({ instructions: z.string().optional(), items: z.array(z.object({ medicineName: z.string().min(1), strength: z.string().optional(), dose: z.string().optional(), frequency: z.string().optional(), route: z.string().optional(), duration: z.string().optional(), instructions: z.string().optional() })).default([]) }).optional(), investigations: z.array(z.object({ name: z.string().min(1), indication: z.string().optional(), instructions: z.string().optional() })).default([]), treatmentPlan: z.string().optional(), followUp: z.object({ dueAt: z.string().optional(), instructions: z.string().optional() }).optional(), status: z.enum(['DRAFT', 'COMPLETED']).default('DRAFT') })
const reviewSchema = z.object({ action: z.enum(['VERIFY', 'EDIT', 'REJECT', 'MARK_UNRELATED']), structuredData: z.record(z.unknown()).optional(), notes: z.string().optional() })
const appointmentSchema = z.object({ caseId: z.string().optional(), doctorId: z.string(), departmentId: z.string().optional(), hospitalId: z.string().optional(), scheduledAt: z.string().datetime() })
const queueSchema = z.object({ caseId: z.string().optional(), departmentId: z.string().optional(), hospitalId: z.string().optional() })
const registrationSchema = z.object({ caseId: z.string().optional(), departmentId: z.string().optional(), hospitalId: z.string().optional() })

type TokenPayload = { sub: string; role: Role; patientId?: string; doctorId?: string }
type AuthRequest = Request & { auth?: TokenPayload }

function signAccessToken(payload: TokenPayload) { return jwt.sign(payload, jwtSecret, { expiresIn: '15m' }) }
function hashToken(value: string) { return crypto.createHash('sha256').update(value).digest('hex') }
function riskForText(text: string): RiskLevel { if (/chest pain|chest discomfort|difficulty breathing|shortness of breath|fainted|unconscious|stroke/i.test(text)) return RiskLevel.EMERGENCY; if (/severe pain|persistent vomiting|high fever|blood in/i.test(text)) return RiskLevel.POTENTIALLY_URGENT; if (/pain|vomit|dizz/i.test(text)) return RiskLevel.MODERATE; return RiskLevel.LOW }
function actionForRisk(level: RiskLevel) { return level === RiskLevel.EMERGENCY ? 'SEEK_EMERGENCY_CARE' : level === RiskLevel.POTENTIALLY_URGENT ? 'PROMPT_CLINICAL_ATTENTION' : level === RiskLevel.MODERATE ? 'ROUTINE_CARE_WITH_WARNING' : 'ROUTINE_CARE' }
function jsonValue(value: unknown): Prisma.InputJsonValue { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue }
function structuredFindings(complaint: string) { const text = complaint.toLowerCase(); const symptoms = ['stomach', 'abdomen', 'abdominal'].some((word) => text.includes(word)) ? ['stomach pain'] : []; if (text.includes('nausea')) symptoms.push('nausea'); if (text.includes('cough')) symptoms.push('cough'); if (text.includes('dizz')) symptoms.push('dizziness'); const duration = text.match(/\d+\s*(?:days?|weeks?)/)?.[0] ?? null; return { symptoms: symptoms.length ? symptoms : ['reported concern'], location: symptoms.includes('stomach pain') ? 'abdomen' : null, duration, severity: null, onset: duration ? 'recent' : null, associatedSymptoms: symptoms.filter((item) => item !== 'stomach pain'), relevantHistory: [], medications: [], allergies: [], clinicalContext: symptoms.includes('stomach pain') || symptoms.includes('nausea') ? 'Gastrointestinal' : 'General Medicine', recommendedDepartment: symptoms.includes('stomach pain') || symptoms.includes('nausea') ? 'Gastroenterology' : 'General Medicine', uncertainties: [], confidence: 0.92 } }
async function audit(actorId: string | undefined, action: string, entityType: string, entityId: string, metadata?: unknown) { await prisma.auditLog.create({ data: { actorId, action, entityType, entityId, metadata: metadata as object ?? undefined } }).catch(() => undefined) }
async function issueTokens(user: { id: string; role: Role; patient?: { id: string } | null; doctor?: { id: string } | null }) { const payload: TokenPayload = { sub: user.id, role: user.role, patientId: user.patient?.id, doctorId: user.doctor?.id }; const accessToken = signAccessToken(payload); const rawRefresh = jwt.sign({ sub: user.id }, refreshSecret, { expiresIn: '30d' }); await prisma.refreshToken.create({ data: { userId: user.id, tokenHash: hashToken(rawRefresh), expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000) } }); return { accessToken, refreshToken: rawRefresh } }

async function requireAuth(request: AuthRequest, response: Response, next: NextFunction) { const value = request.header('authorization')?.replace(/^Bearer\s+/i, ''); if (!value) return response.status(401).json({ error: 'Authentication required' }); try { request.auth = jwt.verify(value, jwtSecret) as TokenPayload; next() } catch { return response.status(401).json({ error: 'Invalid or expired access token' }) } }
function requireRole(role: Role) { return (request: AuthRequest, response: Response, next: NextFunction) => { if (request.auth?.role !== role) return response.status(403).json({ error: 'Insufficient permissions' }); next() } }
async function patientFor(request: AuthRequest) { return request.auth?.patientId ? prisma.patient.findUnique({ where: { id: request.auth.patientId } }) : null }
async function ownedCase(request: AuthRequest, id: string) { const item = await prisma.case.findUnique({ where: { id }, include: { patient: true, department: true, summaries: true, responses: true, symptoms: true, riskAssessments: true, documents: true } }); if (!item || (request.auth?.role === Role.PATIENT && item.patientId !== request.auth.patientId)) return null; return item }
async function ownedDocument(request: AuthRequest, id: string) { const item = await prisma.document.findUnique({ where: { id }, include: { patient: true, case: true, versions: true, reviews: true } }); if (!item || (request.auth?.role === Role.PATIENT && item.patientId !== request.auth.patientId)) return null; return item }

app.get('/health', (_request, response) => response.json({ status: 'ok', service: 'carekare-api', persistence: 'postgresql' }))
app.post('/auth/patient/login', async (request, response, next) => { try { const result = authSchema.safeParse(request.body); if (!result.success) return response.status(400).json({ error: 'Enter an ABHA ID or identity identifier' }); const patient = await prisma.patient.findFirst({ where: { OR: [{ abhaId: result.data.identifier }, { user: { email: result.data.identifier } }] }, include: { user: { include: { patient: true, doctor: true } } } }); if (!patient && !mockAuth) return response.status(401).json({ error: 'Identity not found' }); const resolved = patient ?? await prisma.patient.findFirst({ include: { user: { include: { patient: true, doctor: true } } } }); if (!resolved) return response.status(503).json({ error: 'No demo patient is seeded. Run npm run db:seed.' }); const tokens = await issueTokens(resolved.user); await audit(resolved.userId, 'LOGIN', 'Patient', resolved.id, { mock: mockAuth }); response.json({ ...tokens, user: { id: resolved.userId, role: Role.PATIENT, name: resolved.name, abhaId: resolved.abhaId }, mock: mockAuth }) } catch (error) { next(error) } })
app.post('/auth/doctor/login', async (request, response, next) => { try { const result = authSchema.safeParse(request.body); if (!result.success) return response.status(400).json({ error: 'Enter a doctor ID and password' }); const doctor = await prisma.doctor.findFirst({ where: { OR: [{ user: { email: result.data.identifier } }, { id: result.data.identifier }] }, include: { user: { include: { patient: true, doctor: true } } } }); if (!doctor) return response.status(401).json({ error: 'Invalid doctor credentials' }); if (!mockAuth && (!doctor.user.passwordHash || !result.data.password || !(await bcrypt.compare(result.data.password, doctor.user.passwordHash)))) return response.status(401).json({ error: 'Invalid doctor credentials' }); const tokens = await issueTokens(doctor.user); await audit(doctor.userId, 'LOGIN', 'Doctor', doctor.id, { mock: mockAuth }); response.json({ ...tokens, user: { id: doctor.userId, role: Role.DOCTOR, name: doctor.name, department: doctor.department }, mock: mockAuth }) } catch (error) { next(error) } })
app.post('/auth/refresh', async (request, response, next) => { try { const token = z.string().min(1).safeParse(request.body?.refreshToken); if (!token.success) return response.status(400).json({ error: 'Refresh token required' }); const decoded = jwt.verify(token.data, refreshSecret) as { sub: string }; const record = await prisma.refreshToken.findFirst({ where: { userId: decoded.sub, tokenHash: hashToken(token.data), revokedAt: null, expiresAt: { gt: new Date() } }, include: { user: { include: { patient: true, doctor: true } } } }); if (!record) return response.status(401).json({ error: 'Refresh token is invalid' }); response.json({ accessToken: signAccessToken({ sub: record.user.id, role: record.user.role, patientId: record.user.patient?.id, doctorId: record.user.doctor?.id }) }) } catch (error) { next(error) } })
app.post('/auth/logout', requireAuth, async (request: AuthRequest, response, next) => { try { await prisma.refreshToken.updateMany({ where: { userId: request.auth!.sub, revokedAt: null }, data: { revokedAt: new Date() } }); await audit(request.auth!.sub, 'LOGOUT', 'User', request.auth!.sub); response.status(204).send() } catch (error) { next(error) } })

app.get('/patients/me', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const patient = await patientFor(request); if (!patient) return response.status(404).json({ error: 'Patient profile not found' }); response.json(patient) } catch (error) { next(error) } })
app.get('/patients/me/cases', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { response.json(await prisma.case.findMany({ where: { patientId: request.auth!.patientId }, include: { department: true, summaries: { orderBy: { createdAt: 'desc' }, take: 1 } }, orderBy: { createdAt: 'desc' } })) } catch (error) { next(error) } })
app.get('/patients/me/documents', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { response.json(await prisma.document.findMany({ where: { patientId: request.auth!.patientId }, include: { case: true }, orderBy: { uploadedAt: 'desc' } })) } catch (error) { next(error) } })
app.get('/patients/me/history', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const patient = await patientFor(request); if (!patient) return response.status(404).json({ error: 'Patient profile not found' }); const [cases, documents, consultations, appointments, queues, registrations] = await Promise.all([prisma.case.findMany({ where: { patientId: patient.id }, orderBy: { createdAt: 'desc' } }), prisma.document.findMany({ where: { patientId: patient.id, processingStatus: DocumentStatus.VERIFIED }, orderBy: { uploadedAt: 'desc' } }), prisma.consultation.findMany({ where: { patientId: patient.id }, include: { diagnoses: true, prescriptions: { include: { items: true } }, followUp: true }, orderBy: { createdAt: 'desc' } }), prisma.appointment.findMany({ where: { patientId: patient.id }, orderBy: { scheduledAt: 'asc' } }), prisma.queue.findMany({ where: { patientId: patient.id }, orderBy: { joinedAt: 'desc' } }), prisma.registration.findMany({ where: { patientId: patient.id }, orderBy: { createdAt: 'desc' } })]); response.json({ abhaId: patient.abhaId, cases, documents, consultations, appointments, queues, registrations }) } catch (error) { next(error) } })
app.get('/departments', requireAuth, async (_request, response, next) => { try { response.json(await prisma.department.findMany({ include: { hospital: true }, orderBy: { name: 'asc' } })) } catch (error) { next(error) } })

app.post('/cases', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const result = complaintSchema.safeParse(request.body); if (!result.success) return response.status(400).json({ error: 'Complaint must be at least 3 characters' }); const patient = await patientFor(request); if (!patient) return response.status(404).json({ error: 'Patient profile not found' }); const findings = structuredFindings(result.data.complaint); const riskLevel = riskForText(result.data.complaint); const department = await prisma.department.findFirst({ where: { name: { contains: findings.recommendedDepartment, mode: 'insensitive' } } }); const item = await prisma.case.create({ data: { id: `CK-${new Date().getFullYear()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`, patientId: patient.id, hospitalId: result.data.hospitalId, departmentId: department?.id, status: riskLevel === RiskLevel.EMERGENCY ? CaseStatus.IN_PROGRESS : CaseStatus.AI_ASSESSMENT_COMPLETE, complaint: result.data.complaint, aiFindings: jsonValue(findings), riskLevel, symptoms: { create: findings.symptoms.map((name) => ({ name, location: findings.location ?? undefined, duration: findings.duration ?? undefined, associated: jsonValue(findings.associatedSymptoms) })) }, riskAssessments: { create: { level: riskLevel, action: actionForRisk(riskLevel) } } }, include: { department: true, symptoms: true, riskAssessments: true } }); await audit(request.auth!.sub, 'CASE_CREATED', 'Case', item.id, { riskLevel }); response.status(201).json(item) } catch (error) { next(error) } })
app.get('/cases/:id', requireAuth, async (request: AuthRequest, response, next) => { try { const item = await ownedCase(request, String(request.params.id)); if (!item) return response.status(404).json({ error: 'Case not found or not authorized' }); response.json(item) } catch (error) { next(error) } })
app.put('/cases/:id', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const item = await ownedCase(request, String(request.params.id)); if (!item) return response.status(404).json({ error: 'Case not found or not authorized' }); const complaint = z.string().min(3).max(4000).optional().parse(request.body?.complaint); const updated = await prisma.case.update({ where: { id: item.id }, data: complaint ? { complaint, aiFindings: structuredFindings(complaint), riskLevel: riskForText(complaint) } : {} }); await audit(request.auth!.sub, 'CASE_UPDATED', 'Case', item.id); response.json(updated) } catch (error) { next(error) } })
app.post('/cases/:id/responses', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const item = await ownedCase(request, String(request.params.id)); if (!item) return response.status(404).json({ error: 'Case not found or not authorized' }); const result = responseSchema.safeParse(request.body); if (!result.success) return response.status(400).json({ error: 'A valid answer is required' }); const saved = await prisma.caseResponse.create({ data: { caseId: item.id, questionId: result.data.questionId, answer: jsonValue(result.data.answer) } }); response.status(201).json(saved) } catch (error) { next(error) } })
app.post('/cases/:id/risk-assessment', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const item = await ownedCase(request, String(request.params.id)); if (!item) return response.status(404).json({ error: 'Case not found or not authorized' }); const result = riskSchema.parse(request.body ?? {}); const level = riskForText(`${item.complaint ?? ''} ${JSON.stringify(item.responses)}`); if (level === RiskLevel.EMERGENCY) await prisma.case.update({ where: { id: item.id }, data: { status: CaseStatus.IN_PROGRESS, riskLevel: level } }); const risk = await prisma.riskAssessment.create({ data: { caseId: item.id, level, action: actionForRisk(level), acknowledged: Boolean(result.acknowledged) } }); await audit(request.auth!.sub, level === RiskLevel.EMERGENCY ? 'RISK_WARNING_SHOWN' : 'RISK_ASSESSED', 'Case', item.id, { level }); response.json({ ...risk, emergency: level === RiskLevel.EMERGENCY }) } catch (error) { next(error) } })
app.post('/cases/:id/department', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const item = await ownedCase(request, String(request.params.id)); if (!item) return response.status(404).json({ error: 'Case not found or not authorized' }); const result = departmentSchema.parse(request.body); const level = item.riskLevel ?? RiskLevel.LOW; if (level === RiskLevel.EMERGENCY) return response.status(409).json({ error: 'Emergency cases cannot be routed through ordinary departments' }); if (level === RiskLevel.POTENTIALLY_URGENT && !result.acknowledged) return response.status(409).json({ error: 'Explicit acknowledgement is required for an urgent override' }); const updated = await prisma.case.update({ where: { id: item.id }, data: { departmentId: result.departmentId } }); await audit(request.auth!.sub, 'DEPARTMENT_CHANGED', 'Case', item.id, { departmentId: result.departmentId }); response.json(updated) } catch (error) { next(error) } })
app.post('/cases/:id/summary', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const item = await ownedCase(request, String(request.params.id)); if (!item) return response.status(404).json({ error: 'Case not found or not authorized' }); if (item.riskLevel === RiskLevel.EMERGENCY) return response.status(409).json({ error: 'Emergency guidance must be followed before routine handoff' }); const content = { ...(item.aiFindings as object), mainComplaint: item.complaint, riskLevel: item.riskLevel, recommendedDepartment: (item.aiFindings as { recommendedDepartment?: string } | null)?.recommendedDepartment, disclaimer: 'AI organizes information; a clinician provides diagnosis and treatment.' }; const summary = await prisma.caseSummary.create({ data: { caseId: item.id, content, confidence: 0.92 } }); await prisma.case.update({ where: { id: item.id }, data: { status: CaseStatus.READY_FOR_CONSULTATION } }); await audit(request.auth!.sub, 'CASE_SUMMARY_CREATED', 'Case', item.id); response.json(summary) } catch (error) { next(error) } })

app.get('/doctor/dashboard', requireAuth, requireRole(Role.DOCTOR), async (_request, response, next) => { try { const [activeCases, reportsForReview, completedConsultations, recentPatients] = await Promise.all([prisma.case.count({ where: { status: { in: [CaseStatus.READY_FOR_CONSULTATION, CaseStatus.CONSULTATION_IN_PROGRESS] } } }), prisma.document.count({ where: { processingStatus: DocumentStatus.REVIEW_REQUIRED } }), prisma.consultation.count({ where: { status: 'COMPLETED' } }), prisma.patient.findMany({ take: 5, orderBy: { createdAt: 'desc' }, select: { id: true, name: true, abhaId: true } })]); response.json({ activeCases, reportsForReview, completedConsultations, recentPatients }) } catch (error) { next(error) } })
app.get('/doctor/cases', requireAuth, requireRole(Role.DOCTOR), async (_request, response, next) => { try { response.json(await prisma.case.findMany({ include: { patient: true, department: true, summaries: { orderBy: { createdAt: 'desc' }, take: 1 }, riskAssessments: { orderBy: { createdAt: 'desc' }, take: 1 } }, orderBy: { createdAt: 'desc' } })) } catch (error) { next(error) } })
app.get('/doctor/cases/:id', requireAuth, requireRole(Role.DOCTOR), async (request, response, next) => { try { const item = await prisma.case.findUnique({ where: { id: String(request.params.id) }, include: { patient: true, department: true, summaries: true, responses: { include: { question: true } }, symptoms: true, documents: true, consultations: { include: { diagnoses: true, clinicalNotes: true, prescriptions: { include: { items: true } }, investigations: true, treatmentPlan: true, followUp: true } }, riskAssessments: true } }); if (!item) return response.status(404).json({ error: 'Case not found' }); response.json(item) } catch (error) { next(error) } })
app.get('/doctor/documents', requireAuth, requireRole(Role.DOCTOR), async (_request, response, next) => { try { response.json(await prisma.document.findMany({ where: { processingStatus: DocumentStatus.REVIEW_REQUIRED }, include: { patient: true, case: true, versions: { orderBy: { version: 'desc' }, take: 1 } }, orderBy: { uploadedAt: 'asc' } })) } catch (error) { next(error) } })
app.post('/doctor/consultations', requireAuth, requireRole(Role.DOCTOR), async (request: AuthRequest, response, next) => { try { const result = consultationSchema.safeParse(request.body); if (!result.success) return response.status(400).json({ error: 'Invalid consultation data', details: result.error.flatten() }); const doctor = await prisma.doctor.findUnique({ where: { userId: request.auth!.sub } }); if (!doctor) return response.status(404).json({ error: 'Doctor profile not found' }); const item = await prisma.case.findUnique({ where: { id: result.data.caseId } }); if (!item) return response.status(404).json({ error: 'Case not found' }); if (result.data.status === 'COMPLETED' && result.data.diagnosis.length === 0) return response.status(400).json({ error: 'Doctor confirmation requires at least one diagnosis' }); const consultation = await prisma.consultation.create({ data: { caseId: item.id, patientId: item.patientId, doctorId: doctor.id, clinicalAssessment: result.data.clinicalAssessment, status: result.data.status, completedAt: result.data.status === 'COMPLETED' ? new Date() : undefined, clinicalNotes: result.data.clinicalNotes ? { create: { content: result.data.clinicalNotes, authorId: doctor.id } } : undefined, diagnoses: { create: result.data.diagnosis.map((diagnosis) => ({ ...diagnosis, confirmed: true })) }, prescriptions: result.data.prescription ? { create: { instructions: result.data.prescription.instructions, items: { create: result.data.prescription.items } } } : undefined, investigations: { create: result.data.investigations }, treatmentPlan: result.data.treatmentPlan ? { create: { content: result.data.treatmentPlan } } : undefined, followUp: result.data.followUp ? { create: { dueAt: result.data.followUp.dueAt ? new Date(result.data.followUp.dueAt) : undefined, instructions: result.data.followUp.instructions } } : undefined }, include: { diagnoses: true, prescriptions: { include: { items: true } }, investigations: true, clinicalNotes: true, treatmentPlan: true, followUp: true } }); await prisma.case.update({ where: { id: item.id }, data: { status: result.data.status === 'COMPLETED' ? CaseStatus.CONSULTATION_COMPLETED : CaseStatus.CONSULTATION_IN_PROGRESS } }); await audit(request.auth!.sub, 'CONSULTATION_CREATED', 'Consultation', consultation.id, { status: result.data.status }); response.status(201).json(consultation) } catch (error) { next(error) } })
app.put('/doctor/consultations/:id', requireAuth, requireRole(Role.DOCTOR), async (request: AuthRequest, response, next) => { try { const result = consultationSchema.partial({ caseId: true }).safeParse(request.body); if (!result.success) return response.status(400).json({ error: 'Invalid consultation data' }); const existing = await prisma.consultation.findUnique({ where: { id: String(request.params.id) } }); if (!existing) return response.status(404).json({ error: 'Consultation not found' }); const updated = await prisma.consultation.update({ where: { id: existing.id }, data: { clinicalAssessment: result.data.clinicalAssessment, status: result.data.status, completedAt: result.data.status === 'COMPLETED' ? new Date() : undefined } }); await audit(request.auth!.sub, 'CONSULTATION_UPDATED', 'Consultation', existing.id); response.json(updated) } catch (error) { next(error) } })

app.post('/documents/upload', requireAuth, requireRole(Role.PATIENT), upload.single('file'), async (request: AuthRequest, response, next) => { try { if (!request.file) return response.status(400).json({ error: 'A PDF, JPG, JPEG, or PNG file is required' }); const caseId = z.string().optional().parse(request.body.caseId); const patient = await patientFor(request); if (!patient) return response.status(404).json({ error: 'Patient profile not found' }); if (caseId && !(await ownedCase(request, caseId))) return response.status(403).json({ error: 'Case is not owned by this patient' }); const type = String(request.body.type ?? 'OTHER'); const document = await prisma.document.create({ data: { patientId: patient.id, caseId, type, fileName: request.file.originalname, storagePath: request.file.path, mimeType: request.file.mimetype, fileSize: request.file.size, fileHash: await new Promise<string>((resolve, reject) => { const hash = crypto.createHash('sha256'); const stream = fs.createReadStream(request.file!.path); stream.on('data', (chunk) => hash.update(chunk)); stream.on('end', () => resolve(hash.digest('hex'))); stream.on('error', reject) }), processingStatus: DocumentStatus.UPLOADED } }); await audit(request.auth!.sub, 'DOCUMENT_UPLOADED', 'Document', document.id); response.status(201).json(document) } catch (error) { next(error) } })
app.get('/documents/:id', requireAuth, async (request: AuthRequest, response, next) => { try { const document = await ownedDocument(request, String(request.params.id)); if (!document) return response.status(404).json({ error: 'Document not found or not authorized' }); response.json(document) } catch (error) { next(error) } })
app.get('/documents/:id/original', requireAuth, async (request: AuthRequest, response, next) => { try { const document = await ownedDocument(request, String(request.params.id)); if (!document || request.auth?.role !== Role.DOCTOR && document.patientId !== request.auth?.patientId) return response.status(404).json({ error: 'Document not found or not authorized' }); if (!fs.existsSync(document.storagePath)) return response.status(404).json({ error: 'Original file is unavailable' }); response.type(document.mimeType).sendFile(path.resolve(document.storagePath)) } catch (error) { next(error) } })
app.get('/documents/:id/extraction', requireAuth, async (request: AuthRequest, response, next) => { try { const document = await ownedDocument(request, String(request.params.id)); if (!document) return response.status(404).json({ error: 'Document not found or not authorized' }); response.json({ status: document.processingStatus, rawText: document.rawText, extractedData: document.extractedData, confidence: document.extractionConfidence, versions: document.versions }) } catch (error) { next(error) } })
app.post('/documents/:id/process', requireAuth, async (request: AuthRequest, response, next) => { try { const document = await ownedDocument(request, String(request.params.id)); if (!document) return response.status(404).json({ error: 'Document not found or not authorized' }); const extractedData = document.type === 'PRESCRIPTION' ? { diagnosis: 'Gastroesophageal reflux', medicines: [{ medicineName: 'Pantoprazole', dose: '40 mg', frequency: 'Once daily', duration: '14 days', instructions: 'Before breakfast' }], investigations: [], followUp: '2 weeks' } : document.type === 'IMAGING_REPORT' ? { studyName: 'Abdominal ultrasound', bodyArea: 'Abdomen', findings: 'No acute abnormality in mock report', impression: 'Demo extraction only' } : { results: [{ testName: 'Hemoglobin', value: '12.5', unit: 'g/dL', referenceRange: '12-16 g/dL', flag: 'NORMAL' }] }; const updated = await prisma.document.update({ where: { id: document.id }, data: { processingStatus: DocumentStatus.REVIEW_REQUIRED, classification: document.type, classificationConfidence: 0.94, rawText: 'Mock OCR text extracted from the original document.', extractedData, extractionConfidence: 0.94, versions: { create: { version: document.versions.length + 1, data: extractedData } } } }); await audit(request.auth!.sub, 'DOCUMENT_PROCESSED', 'Document', document.id, { provider: 'mock' }); response.json(updated) } catch (error) { next(error) } })
app.put('/documents/:id/extraction', requireAuth, requireRole(Role.DOCTOR), async (request: AuthRequest, response, next) => { try { const document = await ownedDocument(request, String(request.params.id)); if (!document) return response.status(404).json({ error: 'Document not found' }); const data = jsonValue(z.record(z.unknown()).parse(request.body)); const updated = await prisma.document.update({ where: { id: document.id }, data: { extractedData: data, processingStatus: DocumentStatus.REVIEWED, versions: { create: { version: document.versions.length + 1, data } } }, include: { versions: true } }); await audit(request.auth!.sub, 'EXTRACTION_EDITED', 'Document', document.id); response.json(updated) } catch (error) { next(error) } })
app.post('/documents/:id/review', requireAuth, requireRole(Role.DOCTOR), async (request: AuthRequest, response, next) => { try { const result = reviewSchema.safeParse(request.body); if (!result.success) return response.status(400).json({ error: 'Invalid document review' }); const document = await ownedDocument(request, String(request.params.id)); const doctor = await prisma.doctor.findUnique({ where: { userId: request.auth!.sub } }); if (!document || !doctor) return response.status(404).json({ error: 'Document or doctor not found' }); const status = result.data.action === 'VERIFY' ? DocumentStatus.VERIFIED : result.data.action === 'REJECT' || result.data.action === 'MARK_UNRELATED' ? DocumentStatus.REJECTED : DocumentStatus.REVIEWED; const editedData = result.data.structuredData ? jsonValue(result.data.structuredData) : undefined; const updated = await prisma.$transaction(async (tx) => { if (result.data.action === 'EDIT' && editedData) await tx.documentVersion.create({ data: { documentId: document.id, version: document.versions.length + 1, data: editedData } }); const saved = await tx.document.update({ where: { id: document.id }, data: { processingStatus: status, extractedData: result.data.action === 'EDIT' ? editedData : undefined } }); await tx.documentReview.create({ data: { documentId: document.id, reviewerId: doctor.id, action: result.data.action, notes: result.data.notes } }); return saved }); await audit(request.auth!.sub, `DOCUMENT_${result.data.action}`, 'Document', document.id); response.json(updated) } catch (error) { next(error) } })

app.get('/appointments/availability', requireAuth, async (_request, response, next) => { try { const doctors = await prisma.doctor.findMany({ take: 10, include: { appointments: { where: { scheduledAt: { gte: new Date() }, status: 'BOOKED' } } } }); response.json(doctors.map((doctor) => ({ doctorId: doctor.id, doctorName: doctor.name, specialty: doctor.specialty, department: doctor.department, scheduledAt: new Date(Date.now() + 86400000).toISOString(), available: doctor.appointments.length === 0 }))) } catch (error) { next(error) } })
app.post('/appointments', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const result = appointmentSchema.safeParse(request.body); if (!result.success) return response.status(400).json({ error: 'Invalid appointment details' }); const patient = await patientFor(request); if (!patient) return response.status(404).json({ error: 'Patient not found' }); const appointment = await prisma.appointment.create({ data: { patientId: patient.id, caseId: result.data.caseId, doctorId: result.data.doctorId, departmentId: result.data.departmentId, hospitalId: result.data.hospitalId, scheduledAt: new Date(result.data.scheduledAt) } }); await audit(request.auth!.sub, 'APPOINTMENT_BOOKED', 'Appointment', appointment.id); response.status(201).json(appointment) } catch (error) { next(error) } })
app.get('/appointments', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { response.json(await prisma.appointment.findMany({ where: { patientId: request.auth!.patientId }, include: { doctor: true, department: true }, orderBy: { scheduledAt: 'asc' } })) } catch (error) { next(error) } })
app.put('/appointments/:id/cancel', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const appointment = await prisma.appointment.findFirst({ where: { id: String(request.params.id), patientId: request.auth!.patientId } }); if (!appointment) return response.status(404).json({ error: 'Appointment not found' }); response.json(await prisma.appointment.update({ where: { id: appointment.id }, data: { status: 'CANCELLED' } })) } catch (error) { next(error) } })
app.post('/queues/join', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const result = queueSchema.parse(request.body); const patient = await patientFor(request); if (!patient) return response.status(404).json({ error: 'Patient not found' }); const count = await prisma.queue.count({ where: { status: 'WAITING', departmentId: result.departmentId } }); const queue = await prisma.queue.create({ data: { patientId: patient.id, caseId: result.caseId, departmentId: result.departmentId, hospitalId: result.hospitalId, token: `A${String(count + 1).padStart(2, '0')}`, position: count + 1 } }); await audit(request.auth!.sub, 'QUEUE_JOINED', 'Queue', queue.id); response.status(201).json(queue) } catch (error) { next(error) } })
app.get('/queues/:id', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const queue = await prisma.queue.findFirst({ where: { id: String(request.params.id), patientId: request.auth!.patientId } }); if (!queue) return response.status(404).json({ error: 'Queue entry not found' }); response.json(queue) } catch (error) { next(error) } })
app.get('/queues/:id/status', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const queue = await prisma.queue.findFirst({ where: { id: String(request.params.id), patientId: request.auth!.patientId } }); if (!queue) return response.status(404).json({ error: 'Queue entry not found' }); response.json({ token: queue.token, position: queue.position, status: queue.status }) } catch (error) { next(error) } })
app.post('/queues/:id/cancel', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const queue = await prisma.queue.findFirst({ where: { id: String(request.params.id), patientId: request.auth!.patientId } }); if (!queue) return response.status(404).json({ error: 'Queue entry not found' }); response.json(await prisma.queue.update({ where: { id: queue.id }, data: { status: 'CANCELLED' } })) } catch (error) { next(error) } })
app.post('/registrations', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const result = registrationSchema.parse(request.body); const patient = await patientFor(request); if (!patient) return response.status(404).json({ error: 'Patient not found' }); const registration = await prisma.registration.create({ data: { patientId: patient.id, caseId: result.caseId, departmentId: result.departmentId, hospitalId: result.hospitalId, registrationNumber: `REG-${Date.now().toString().slice(-8)}` } }); await audit(request.auth!.sub, 'REGISTRATION_CREATED', 'Registration', registration.id); response.status(201).json(registration) } catch (error) { next(error) } })
app.get('/registrations', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { response.json(await prisma.registration.findMany({ where: { patientId: request.auth!.patientId }, orderBy: { createdAt: 'desc' } })) } catch (error) { next(error) } })
app.get('/registrations/:id', requireAuth, requireRole(Role.PATIENT), async (request: AuthRequest, response, next) => { try { const registration = await prisma.registration.findFirst({ where: { id: String(request.params.id), patientId: request.auth!.patientId } }); if (!registration) return response.status(404).json({ error: 'Registration not found' }); response.json(registration) } catch (error) { next(error) } })

app.use((_request, response) => response.status(404).json({ error: 'Route not found' }))
app.use((error: unknown, _request: Request, response: Response, _next: NextFunction) => { console.error(error); const message = error instanceof Error ? error.message : ''; if (message.includes("Can't reach database server") || message.includes('PrismaClientInitializationError')) return response.status(503).json({ error: 'Database unavailable. Start PostgreSQL and run the seed command.' }); if (error instanceof multer.MulterError || message.includes('File type')) return response.status(400).json({ error: 'Upload a PDF, JPG, JPEG, or PNG file up to 10 MB' }); if (error instanceof Prisma.PrismaClientKnownRequestError) return response.status(400).json({ error: 'The requested record or relationship is invalid' }); response.status(500).json({ error: 'Unexpected server error' }) })
const isTestProcess = process.argv.some((argument) => argument === '--test' || argument.includes('test_runner'))
if (process.env.NODE_ENV !== 'test' && !isTestProcess) app.listen(port, () => console.log(`CareKare API listening on http://localhost:${port}`))
export { app, prisma, riskForText, structuredFindings }
